name: Build Documentation

on:

  # Trigger on push or merge to main, or manually
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      
      # Checkout branch
      - uses: actions/checkout@v3
      
      # Install Sphinx and Sphinx theme
      - name: Install Sphinx
        run: pip install sphinx==5.3.0
      - name: Install theme
        run: pip install pydata-sphinx-theme
        
      # Build docs using Sphinx
      - name: Sphinx build
        working-directory: ./docs
        run: ./make.bat html
      
      # Upload documentation as artifact
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .docs/build/html
          
  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
